---
output: hugodown::md_document
title: "Data Disasters"
subtitle: ""
summary: "Pitfalls moving from Stats 101 to the real world"
authors: []
tags: [data]
categories: [data]
date: 2021-07-31
lastmod: 2021-07-31
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: "A [Simpson's Paradox](https://en.wikipedia.org/wiki/Simpson%27s_paradox)-esque data disaster"
  focal_point: ""
  preview_only: true

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: ["data-disasters"]
---

Every summer, I'm always excited to start seeing a slew of job announcements from fresh college graduates announcing where they'll be beginning their careers as data professionals. This influx of new talent and energy is always an interesting opportunity to reflect on the beginning of my own career and, more specifically, the experience of moving between data analysis as its taught as an academic discipline and data analysis in the real world. 

As I mentioned in my [Toronto Data Workshop](https://www.youtube.com/watch?v=VP3BBZ7poc0) interview back in February, my personal academic background skewed towards the theoretical. I spent much more time in college proving theorems than working applied problems. I may be biased, but overall I'm grateful.  

## Data

Understanding data management and data wrangling is an undeniable prerequisite to analytics. You can be the most brilliant methodologist ever but achieve nonsensical results if you misunderstand what the data you are working with actually represents or manage to distort it in the wrangling process.

- **Data Dalliances**: Misinterpreting or misuing data based on how it was collected or what it represents 
- **Computational Quandaries**: Letting computers do what you said and not what you meant

## Analysis 

With a solid foundation in data and tools, 

- **Egregious Aggregations**: Losing critical information when information is condensed
- **Vexing Visualization**: Confusing ourselves or others with plotting choices
- **Incredible Inferences**: Drawing incorrect conclusions for analytical results
- **Cavalier Causality**: Falling prey to spurious correlations masquerading as causality 
- **Mindless Modeling**: Failing to get the most value out of models by not tailoring the features, targets, and performance metrics 
- **Alternative Algorithms**: Lacking an understanding of alternative methods which may be better suited for the problem at hand

## Workflow 

So you did a great analysis, does it matter? Embracing a good workflow in the "moment before" and "moment after" a data anaylsis is critical to get the most bang for your buck. This can cover everything from carefully deciding what questions are worth answering to begin with and then answering them in the most credible, sustainable way possible.

- **Futile Findings**: Asking and answering questions that aren't useful
- **Complexifying Code**: Making projects unwieldy or more difficult to understand than necessary
- **Rejecting Reproducibility**: Working inefficiently instead of an efficient, reproducible, and sharable workflow



